trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'Build&Push'
  jobs:
  - job: 'Build_Image'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'TODO' 
        command: 'login'
        ## TODO